### ISSUE TITLE
Input field locked after 1 right answer

### ISSUE THREAD

**Issue by ds2k5** [Top-Ranger/harbour-vocabulary#1]
Hi,
using: Sailfish OS 2.0.4.14
I made a little CVS file (comma)
[fra.zip](https://github.com/Top-Ranger/harbour-vocabulary/files/547378/fra.zip)
and IMPORT it.
If i choose that the answer is right, then is the Input Flield locked
can not delete the last imput.

![20161024114746](https://cloud.githubusercontent.com/assets/11292286/19641194/159091fc-99e0-11e6-96d1-f46be850e35b.jpg)

What did i wrong ?
Thanks

**Comment by ds2k5** [comment]
SORRY if i press longer in the Input field it will be cleared

**Comment by Top-Ranger** [comment]
Seems to be a known issue: https://lists.sailfishos.org/pipermail/devel/2014-May/004151.html
I will look if I can find some workaround.

**Comment by Top-Ranger** [comment]
I've run some testing and it seems that disabling the prediction does the job.
