### ISSUE TITLE
Add options for selecting vocabulary for training

### ISSUE THREAD

**Issue by Top-Ranger** [Top-Ranger/harbour-vocabulary#11]
Reported by 'duckz' through the Jolla store:

Add options for training mode, e.g.:
 - [x] Only select words over a threshold
 - [x] End after an amount of words (and show stats)
 - [x] Select language for training
 - [x] Select translation direction (https://github.com/Top-Ranger/harbour-vocabulary/issues/7)
 - [x] Select only words from a specific date range (sfbg, see comment)

**Comment by Top-Ranger** [comment]
Additional option:
* Select language for training

**Comment by Top-Ranger** [comment]
From https://github.com/Top-Ranger/harbour-vocabulary/issues/7:
* Select translation direction

**Comment by sfbg** [comment]
Select only words from a specific date range, i.e. yesterday, current month, from-to date, etc.
