### ISSUE TITLE
v1.4: Update from v1.3 duplicates the last entered vocabulary

### ISSUE THREAD

**Issue by sfbg** [Top-Ranger/harbour-vocabulary#13]
After the update, the last vocabulary I have previously entered was duplicated in the list.

**Comment by Top-Ranger** [comment]
Thanks for reporting

It seems that this slipped through my personal testing, however I have the same problem. I'll investigate it, but for now you have to delete that vocabulary manually.

Depending on where there issue is I might correct it in a later version (this won't help anyone who has upgraded it) or leave it unchanged as an artefact (if it would change the upgrade process too much).

**Comment by Top-Ranger** [comment]
Drafting new release to push this before others updating
