### ISSUE TITLE
Hide multiple language UI elements if only one language exists

### ISSUE THREAD

**Issue by sfbg** [Top-Ranger/harbour-vocabulary#15]
Probably most users will use the app for one language only.
Thus, it would be nice to not show the UI related to multiple languages (and use defaults) if there is only one language set up in the app.

**Comment by Top-Ranger** [comment]
Which UI elements are you referring at? Especially since the new combo box update (https://github.com/Top-Ranger/harbour-vocabulary/pull/14) the elements should be minimal. Plus once you selected a language while adding a vocabulary / selected a language for training it will remember that language.

**Comment by sfbg** [comment]
I am referring to all UI elements in  "Start training" and "Add vocabulary" that have to do with selecting a language. 

If there is only one language, there is no need to clutter the UI with those.

Naturally, the main item "Manage languages" should be always visible in case the user wants to add a new one.

**Comment by Top-Ranger** [comment]
I've added this for the training.

For adding vocabulary I let the selection in as it is also possible to create a new language in that menu.
