### ISSUE TITLE
Text size issue on some screens

### ISSUE THREAD

**Issue by sfbg** [Top-Ranger/harbour-vocabulary#22]
On the Sony Xperia X screen, labels are the right size, but text is too small:

![screenshot_20170930_001](https://user-images.githubusercontent.com/24361624/31046792-a2e43d3e-a5ff-11e7-870c-891ca218034f.png)

**Comment by sfbg** [comment]
It seems that Label instead of Text as item type would solve the issue.

**Comment by Top-Ranger** [comment]
I will look into it (even though I don't have an Xperia)...

The problem with Labels is - if I remember correctly - that they do not wrap text, so long vocabulary will go off screen.

The solution will probably be to set an explicit font.pixelsize, although I have to test it somehow (I may need your help with that).

**Comment by sfbg** [comment]
I can gladly test it. My MerSDK VM is somehow broken and can't build for ARM, otherwise I could have tried to fix  and test it myself.

**Comment by Top-Ranger** [comment]
It seems that Labels actually work.

I've attached a version with the Text elements replaced by Label elements. Can you test it please? Thanks for your help.

[harbour-vocabulary-1.8-1.armv7hl.rpm.gz](https://github.com/Top-Ranger/harbour-vocabulary/files/1357307/harbour-vocabulary-1.8-1.armv7hl.rpm.gz)

EDIT: You need to unzip it first:
```
gunzip harbour-vocabulary-1.8-1.armv7hl.rpm.gz
```

**Comment by sfbg** [comment]
I've tested in on the Xperia. The problem is now solved.

**Comment by Top-Ranger** [comment]
Thanks a lot
