### ISSUE TITLE
Import more than 172 items possible ?

### ISSUE THREAD

**Issue by ds2k5** [Top-Ranger/harbour-vocabulary#4]
Hello,
i expand my CSV File (comma).
Now i have more than 172 items.
But the Import fails.
Is it possible that the Import fail if there more than 172 items in it
or is my file damaged ?
Thanks

unsing Version 1.0 on sailfish os 2.0.4.14
[vocabulary..zip](https://github.com/Top-Ranger/harbour-vocabulary/files/614287/vocabulary.zip)

---------

i update to 1.1 now fails the import at 195 items, with the same file
![import_error](https://cloud.githubusercontent.com/assets/11292286/20647361/0d5f79da-b493-11e6-9c2c-24847ba5515e.jpg)

**Comment by ds2k5** [comment]
my fault, sorry ! 
had empty lines in it!

**Comment by Top-Ranger** [comment]
Thanks for the notice! Since 1.1 empty lines shouldn't bring problems any more.
