### ISSUE TITLE
Date of entry for vocabulary

### ISSUE THREAD

**Issue by sfbg** [Top-Ranger/harbour-vocabulary#5]
It would be useful to save into the DB when a vocabulary was added.
Potential uses later:
* List in that order
* Train with entries only from a specific period

**Comment by Top-Ranger** [comment]
Definitely good ideas! The listing should be easy to implement, the training would need some UI changes (and internal changes) I'm not sure how to add that the best way.

**Comment by sfbg** [comment]
Yes, the GUI implementation has to be considered in more detail. Bit it is good to have the info in the DB as infrastructure for future developments, even if they are not implemented immediately.
One more potential use of the field would be to automatically increase the score with time passed, to make sure that older vocabulary is tested again as the learner might have forgotten it.

**Comment by Top-Ranger** [comment]
The date of creation (as well as the date of the last modification) is now saved into the database.

I have to look how to use the information - most likely I will start implementing a filter for the test mode once I reworked the test mode (possibly after https://github.com/Top-Ranger/harbour-vocabulary/issues/10).

If you have some specific wishes don't hesitate to open a bug report.
