### ISSUE TITLE
[Enhancement] Possibilty to set which translation is tested in training mode

### ISSUE THREAD

**Issue by sfbg** [Top-Ranger/harbour-vocabulary#7]
It is good to have the current setting of showing either the "from" or "to" entry. 
But for learning purposes it should be possible to set if you want to have only the "from" or only the "to" language tested.

**Comment by Bu33zhidao** [comment]
Yes, that would be great!
Or e.g.: Vocabularies with a high priority are shown from both sides to assist learning; once the priority drops below some threshold only one side of the card will be presented.

**Comment by Top-Ranger** [comment]
I like the ideas - I will look what I can do

**Comment by Top-Ranger** [comment]
Added suggestion to https://github.com/Top-Ranger/harbour-vocabulary/issues/11
